### ISSUE TITLE
deployment : Available-False-MinimumReplicasUnavailable(Type-status-reason)

### ISSUE THREAD

**Issue by jeff87101223** [WISE-PaaS/wp-handbook#10]
1.docker build -t {image} .
2.docker push {image}
3.kubectl apply -f {config}
4.kubectl get all
執行以上步驟後，在deployment describe 裡面出現 Event 問題，後pod就無法出現。
附上截圖:
![iZB2dhw](https://user-images.githubusercontent.com/16678646/77885985-a0693180-729a-11ea-8d21-afdc2b774dd4.png)

**Comment by heynats** [comment]
see issue #11
