### ISSUE TITLE
Quota pods exceed

### ISSUE THREAD

**Issue by allguitars** [WISE-PaaS/wp-handbook#11]
A student reported that he cannot create any new pods after applying the configs.
Here is the screen capture provided by the student.

![temp](https://user-images.githubusercontent.com/38038238/77893353-61d97400-72a6-11ea-9a1b-904a1daa580b.jpg)

But when I checked the management portal, the number shown on the page has not exceeded the quota yet.

![Image-20200330-008](https://user-images.githubusercontent.com/38038238/77893785-f7750380-72a6-11ea-88db-fae86f63df8f.png)

**Comment by heynats** [comment]
suspecting #10 is related

**Comment by heynats** [comment]
Expanded computing resources for the training cluster. Will continue to monitor the situation for a while.
