### ISSUE TITLE
final projects

### ISSUE THREAD

**Issue by gbwade** [WISE-PaaS/wp-handbook#12]
1.docker build -t {image} .
2.docker push {image}
3.kubectl apply -f {config}
4.kubectl get all
執行以上步驟後，在deployment describe 裡面出現 Event 問題，然後再去describe replicaset之後她出現了Quota pods exceed, usage: 251,quota: 250。
[https://imgur.com/j9I6vMo](url)

**Comment by heynats** [comment]
same issue as #11
