### ISSUE TITLE
too many connections for database "c4799efa-5899-11ea-8729-f6bfce9fbbfd"

### ISSUE THREAD

**Issue by gbwade** [WISE-PaaS/wp-handbook#13]
![igRScO4](https://user-images.githubusercontent.com/16678646/77926811-21dfb480-72d9-11ea-9b79-9c325d3fa4f0.png)

**Comment by heynats** [comment]
螢幕截圖和issue標題不符，能提供更多訊息嗎？

**Comment by gbwade** [comment]
https://imgur.com/igRScO4

Stanley Yeh <notifications@github.com> 於 2020年3月30日 週一 下午7:02寫道：

**Comment by gbwade** [comment]
不好意思，這是問題的結圖


wei jin shi <q2315840@gmail.com> 於 2020年3月30日 週一 下午7:06寫道：

**Comment by heynats** [comment]
issue resolved after expanding database connection capacity by switching to a dedicated database.
