### ISSUE TITLE
Pod crashloopbackoff causing 502 bad gateway

### ISSUE THREAD

**Issue by Tzuyuchen0423** [WISE-PaaS/wp-handbook#3]
在重複build完 一直找不到錯誤 也把docker 帳號的版本紀錄也刪掉了 還是會出現502
已經把版本號改到10版了 請問是哪裡出了問題?
pod 還會出現crashloopbackoff  是哪裡漏掉了?

**Comment by heynats** [comment]
通常若pod因任何錯誤無法生成的話，存取應用的URL就會收到502錯誤，因為應用並未正確執行。
Pod create fail時常見的錯誤有：
- CrashLoopBackOff, 應用一直因錯誤重啟，導致pod無法進入正常狀態
- ImagePullBackOff, pod無法下載鏡像，仍在嘗試
- ErrImagePull, 無法使用配置中定義的鏡像生成container建立pod
若發生CrashLoopBackOff的錯誤狀態，建議先delete deployment並免K8s一直耗費資源嘗試建立pod，先在本地端確定container可被啟動運作後再行deploy。

請使用describe指令詳細錯誤的event說明，例：
<img width="1440" alt="Screen Shot 2020-03-30 at 10 45 20 AM" src="https://user-images.githubusercontent.com/16678646/77881053-a6f2ab80-7290-11ea-8f12-9f2855c3123f.png">

另一個常見的非正常pod狀態就是“evicted”。當pod運行時所需的資源超過環境能提供的資源時，例如用量超過在deployment yaml裡定義的cpu request/limit配置，K8s就會將其驅逐(evict)。
<img width="750" alt="Screen Shot 2020-03-30 at 10 40 24 AM" src="https://user-images.githubusercontent.com/16678646/77881932-87f51900-7292-11ea-934d-4f340640e1cb.png">

平台上常見的pod eviction原因為ephemeral-storage用量超過上限(如上圖)。一般來說container需要使用ephemeral-storage空間存放暫存的log，而在EnSaaS的配置中我們允許container使用128MB來存放logs。若是一個deployment request 64MB的ephemeral-storage，當應用執行時產生的log超過64MB時K8s就會將其驅逐。**因此建議使用EnSaaS時ephemeral-storage request不得小於128MB**

**Comment by heynats** [comment]
Debugging procedures provided. Closing this ticket for inactivity
