### ISSUE TITLE
Dashboard cannot use internal host to connect to PostgreSQL

### ISSUE THREAD

**Issue by B10601032-Training** [WISE-PaaS/wp-handbook#5]
使用iot-home-k8s-level2-secret內含的internalHosts: 10.0.9.102及其帳戶資訊 無法連線至Dashboard
失敗時間：2020/3/19 17:00~2020/3/20 12:00

![1585539578598](https://user-images.githubusercontent.com/62495982/77873286-1dd17980-727c-11ea-8164-c03f55c7a805.jpg)

![image](https://user-images.githubusercontent.com/62495982/77873730-66d5fd80-727d-11ea-835e-ec52a561f059.png)

![image](https://user-images.githubusercontent.com/62495982/77873520-cb448d00-727c-11ea-9bbd-284f68046986.png)

![image](https://user-images.githubusercontent.com/62495982/77873558-ea431f00-727c-11ea-8a77-3be242291413.png)

![image](https://user-images.githubusercontent.com/62495982/77873593-fd55ef00-727c-11ea-9372-0c3a81ccc4a5.png)

**Comment by heynats** [comment]
經用戶反饋，當下改成使用external host就可以連線。
除了host以外其他參數維持不變。

**Comment by heynats** [comment]
issue uneasy to reproduce, will put this on observation.
close for now.
